Replace text node by ace editor code node
igor-korotkov/Activiti pull request #1
Opened 2017-06-06 09:53 UTC by SergeyShkuratko

2017-06-15 10:19 UTC, igor-korotkov requested changes

2017-06-15 10:19 UTC, onecupofspam commented on install-bpm.bat
> +set TOMCAT_PATH=D:\work\projects\scorecard\deploy\tomcat
это код специфичный для тебя

2017-06-15 10:19 UTC, onecupofspam commented on modules/activiti-webapp-explorer2/src/main/webapp/editor-app/ace/theme-monokai.js
> +define("ace/theme/monokai",["require","exports","module","ace/lib/dom"],function(e,t,n){t.isDark=!0,t.cssClass="ace-monokai",t.cssText=".ace-monokai .ace_gutter {background: #2F3129;color: #8F908A}.a
давай по умолчанию светлую тебя возьмем, чтобы не выбиваться из стиля моделера
та, что в кубе в редакторах кода используется, можно

2017-06-15 10:19 UTC, onecupofspam commented on modules/activiti-webapp-explorer2/src/main/webapp/editor-app/configuration/properties-default-controllers.js
> +var KisBpmBeanSelectCtrl = [ '$scope', '$modal', function($scope, $modal) {
это точно часть этого тикета?

2017-06-15 10:19 UTC, onecupofspam commented on modules/activiti-webapp-explorer2/src/main/webapp/editor-app/configuration/properties/bean-select.css
> +input[type="text"]{
форматирование одинаковое сделай везде, как принято
пробелы там etc

2017-06-15 10:19 UTC, onecupofspam commented on modules/activiti-webapp-explorer2/src/main/webapp/editor-app/configuration/properties/bean-select.html
> +<div class="modal" ng-controller="KisBpmTextPropertyPopupCtrl">
не тот тикет?

2017-06-15 10:19 UTC, onecupofspam commented on modules/activiti-webapp-explorer2/src/main/webapp/editor-app/configuration/properties/bean-select.js
> +          console.log(item.paramValue);
убери

2017-06-15 10:19 UTC, onecupofspam commented on modules/activiti-webapp-explorer2/src/main/webapp/editor-app/configuration/properties/bean-select.js
> +    result = result + "{\"paramName\": \"" + paramName + "\", \"paramValue\": \"" + paramValue + "\"}";
если в paramValue пользователь введет кавычки, это дальше упадет, заэскейпь их
т.к. груви будет использоваться, то кавычки там запросто могут оказаться

2017-06-15 10:19 UTC, onecupofspam commented on modules/activiti-webapp-explorer2/src/main/webapp/editor-app/configuration/properties/bean-select.js
> +    argsString +
здесь тоже либо эскейпить, либо наоборот анэскейпить кавычки надо будет

2017-06-22 13:21 UTC, SergeyShkuratko commented on modules/activiti-webapp-explorer2/src/main/webapp/editor-app/ace/theme-monokai.js
> +define("ace/theme/monokai",["require","exports","module","ace/lib/dom"],function(e,t,n){t.isDark=!0,t.cssClass="ace-monokai",t.cssText=".ace-monokai .ace_gutter {background: #2F3129;color: #8F908A}.a
+

2017-06-26 10:24 UTC, merged